import type { Booking, Money, Review, SearchResult } from "@/lib/types";

function dzd(amount: number): Money {
  return { currency: "DZD", amount };
}

export const mockSearchResults: SearchResult[] = [
  {
    id: "demo-ahmed",
    mode: "carpool",
    coverImageUrl:
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=80",
    fromLabel: "Algiers (Kharouba)",
    toLabel: "Oran (El Bahia)",
    pickupLabel: "Pickup: Sogral — Caroubier terminal",
    dropoffLabel: "Drop-off: Yaghmoracen — opposite the public pharmacy",
    departureTime: "08:00",
    arrivalTime: "12:30",
    durationLabel: "4h 30m",
    dateLabel: "Oct 24, 2024",
    pricePerSeat: dzd(1500),
    seatsLeft: 3,
    driverName: "Ahmed",
    driverRating: 4.8,
    vehicleLabel: "Dacia Logan • White",
    luggageIncluded: true,
    instantBooking: false,
    womenOnly: false,
  },
  {
    id: "demo-taharat",
    mode: "bus",
    providerName: "Taharat Transport",
    coverImageUrl:
      "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=900&q=80",
    serviceClass: "Comfort",
    fromLabel: "Algiers (Sogral)",
    toLabel: "Oran (Yaghmoracen)",
    departureTime: "09:00",
    arrivalTime: "13:45",
    durationLabel: "4h 45m",
    dateLabel: "Oct 24, 2024",
    baseFare: dzd(1200),
    serviceFee: dzd(50),
    availableSeats: 14,
    instantConfirmation: true,
  },
  {
    id: "demo-sntf",
    mode: "train",
    providerName: "SNTF",
    coverImageUrl:
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=900&q=80",
    serviceClass: "Standard",
    fromLabel: "Algiers (Agha)",
    toLabel: "Oran (Rail Station)",
    departureTime: "07:15",
    arrivalTime: "12:20",
    durationLabel: "5h 05m",
    dateLabel: "Oct 24, 2024",
    baseFare: dzd(900),
    serviceFee: dzd(25),
    availableSeats: 40,
    instantConfirmation: true,
  },
  {
    id: "demo-meriem",
    mode: "carpool",
    coverImageUrl:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80",
    fromLabel: "Algiers Center",
    toLabel: "Oran Center",
    pickupLabel: "Pickup: Algiers Center",
    dropoffLabel: "Drop-off: Oran Center",
    departureTime: "06:30",
    arrivalTime: "11:00",
    durationLabel: "4h 30m",
    dateLabel: "Oct 24, 2024",
    pricePerSeat: dzd(1600),
    seatsLeft: 0,
    driverName: "Meriem B.",
    driverRating: 4.6,
    vehicleLabel: "Hyundai Accent • Grey",
    luggageIncluded: false,
    instantBooking: true,
    womenOnly: true,
  },
];

export const mockBookings: Booking[] = [
  {
    id: "bk-rx-9283-lz",
    mode: "bus",
    status: "confirmed",
    fromLabel: "Algiers",
    toLabel: "Oran",
    dateLabel: "Oct 24, 2024",
    departureTime: "08:30",
    arrivalTime: "13:30",
    seatLabel: "12A (Window)",
    seatsCount: 1,
    baseFare: dzd(1200),
    serviceFee: dzd(50),
    totalPrice: dzd(1250),
    referenceCode: "RX-9283-LZ",
    providerOrDriverName: "Taharat Transport",
    payment: { method: "edahabia", status: "captured" },
    originDetail: "Sogral Station — Caroubier",
    destinationDetail: "Gare routière Oran — Yaghmoracen",
    durationLabel: "5h 00m",
    serviceClass: "Comfort",
    boardingPointTitle: "Sogral Algiers — Caroubier",
    boardingPointBody:
      "Arrive at least 30 minutes before departure. Present your digital ticket at the assigned platform. Luggage assistance is available at the main hall.",
    contextBackHref: "/bus/demo-taharat",
  },
  {
    id: "bk-px-4421-qr",
    mode: "carpool",
    status: "awaiting_approval",
    fromLabel: "Algiers",
    toLabel: "Constantine",
    dateLabel: "Oct 26, 2024",
    departureTime: "10:00",
    arrivalTime: "14:30",
    seatLabel: "Rear right seat",
    seatsCount: 1,
    baseFare: dzd(1200),
    serviceFee: dzd(0),
    totalPrice: dzd(1200),
    referenceCode: "PX-4421-QR",
    providerOrDriverName: "Sarah (Driver)",
    payment: { method: "cash", status: "not_required" },
    pickupDetail: "Hydra — Rond-point Birtouta (exact pin shared after confirmation)",
    dropoffDetail: "Constantine — Place des Martyrs (north side)",
    vehicleLabel: "Dacia Logan • White • 12345 116 16",
    durationLabel: "4h 30m",
    boardingPointTitle: "Meeting point (after driver accepts)",
    boardingPointBody:
      "The driver will confirm your request first. You’ll receive the exact pickup pin and can message the driver in the app. Be ready 5 minutes before the agreed time.",
    contextBackHref: "/search?mode=carpool",
  },
  {
    id: "bk-tx-3312-zz",
    mode: "train",
    status: "confirmed",
    fromLabel: "Algiers",
    toLabel: "Oran",
    dateLabel: "Oct 24, 2024",
    departureTime: "07:15",
    arrivalTime: "12:20",
    seatLabel: "Coach 2 • 18A (Window)",
    seatsCount: 1,
    baseFare: dzd(900),
    serviceFee: dzd(25),
    totalPrice: dzd(925),
    referenceCode: "TX-3312-ZZ",
    providerOrDriverName: "SNTF",
    payment: { method: "cib", status: "captured" },
    originDetail: "Gare d’Agha — Voie 3",
    destinationDetail: "Gare d’Oran — Hall principal",
    durationLabel: "5h 05m",
    serviceClass: "Standard",
    boardingPointTitle: "Boarding — Gare d’Agha",
    boardingPointBody:
      "Arrive 45 minutes early for security check. Have your ID and e-ticket QR ready. Coach and seat are printed on your ticket.",
    contextBackHref: "/train/demo-sntf",
  },
  {
    id: "bk-hx-1102-aa",
    mode: "bus",
    status: "completed",
    fromLabel: "Oran",
    toLabel: "Algiers",
    dateLabel: "Oct 12, 2024",
    departureTime: "09:00",
    arrivalTime: "13:45",
    seatLabel: "08B",
    seatsCount: 1,
    baseFare: dzd(2400),
    serviceFee: dzd(50),
    totalPrice: dzd(2450),
    referenceCode: "HX-1102-AA",
    providerOrDriverName: "Taharat Transport",
    payment: { method: "cib", status: "captured" },
    originDetail: "Gare routière Oran",
    destinationDetail: "Sogral Alger",
    durationLabel: "4h 45m",
    contextBackHref: "/search?mode=bus",
  },
];

export const mockReviews: Review[] = [
  {
    id: "rv-1",
    bookingId: "bk-rx-9283-lz",
    rating: 5,
    comment: "Trajet ponctuel et confortable. Service très pro.",
    createdAtLabel: "Oct 24, 2024",
    authorName: "Amine R.",
  },
  {
    id: "rv-2",
    bookingId: "bk-hx-1102-aa",
    rating: 4,
    comment: "Bon trajet, mais un léger retard au départ.",
    createdAtLabel: "Oct 13, 2024",
    authorName: "Imane L.",
  },
];
